POO_MVC/Controllers/LoginController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using POO_MVC.Models;

namespace POO_MVC.Controllers
{
    public class LoginController : Controller
    {
        protected static string login = null;
        protected static bool logado = false;

        public IActionResult Index()
        {
            ViewBag.Login = login;
            ViewBag.Logado = logado;
            return View();
        }



        public IActionResult Logar(IFormCollection form)
        {

            Participante pMetodos = new Participante();
            Musico mMetodos = new Musico();

            if ((form["Email"]).ToString().Contains("@") && (form["Email"]).ToString().Contains(".com"))
            {
                if (pMetodos.Logar((form["Email"]).ToString(), (form["Senha"]).ToString()))
                {
                    logado = true;
                    login = $"Login realizado com sucesso. Bem vindo!";
                }
                else
                {
                    logado = false;
                    login = $"Usuario ou senha inválido. Tente novamente";
                }
            }
            else
            {
                if (mMetodos.Logar((form["Email"]).ToString(), (form["Senha"]).ToString()))
                {
                    logado = true;
                    login = $"Login realizado com sucesso. Bem vindo!";
                }
                else
                {
                    logado = false;
                    login = $"Usuario ou senha inválido. Tente novamente";
                }
            }


            return LocalRedirect("~/Login");
        }
    }
}

POO_MVC/Controllers/RegistroEventoController.cs
using Microsoft.AspNetCore.Mvc;

namespace POO_MVC.Controllers
{
    public class RegistroEventoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

POO_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POO_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        @* <div class="grid container_header">
            <img class="logo" src="img/logo 1.svg" alt="logo divina espaco facshion">
            <nav class="menu_principal">
            <a href="">home</a>
            <a href="">masculino</a>
            <a href="">feminino</a>
            <a href="">contato</a>
            </nav>
            </div> *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POO_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                asp-action="Index">Login</a>
                        </li>
                        @if (ViewBag.Logado == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RegistroEvento"
                                asp-action="Index">Registro de eventos</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
        &copy; 2021 - POO_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>